/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'latitude' : number,
  'resolved' : boolean,
  'description' : string,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'locationName' : string,
}
export interface UserProfile {
  'username' : string,
  'emergencyContact' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'safeZoneCenterLat' : number,
  'safeZoneCenterLng' : number,
  'alertStartHour' : bigint,
  'alarmSoundEnabled' : boolean,
  'safeZoneRadius' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlert' : ActorMethod<[Alert], undefined>,
  'addLocation' : ActorMethod<[Location], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLocationHistory' : ActorMethod<[], Array<Location>>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDeviceOnline' : ActorMethod<[], boolean>,
  'resolveAlert' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSettings' : ActorMethod<[UserSettings], undefined>,
  'updateDeviceStatus' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];