/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Alert = IDL.Record({
  'latitude' : IDL.Float64,
  'resolved' : IDL.Bool,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'locationName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'emergencyContact' : IDL.Text,
  'email' : IDL.Text,
});
export const UserSettings = IDL.Record({
  'safeZoneCenterLat' : IDL.Float64,
  'safeZoneCenterLng' : IDL.Float64,
  'alertStartHour' : IDL.Nat,
  'alarmSoundEnabled' : IDL.Bool,
  'safeZoneRadius' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlert' : IDL.Func([Alert], [], []),
  'addLocation' : IDL.Func([Location], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocationHistory' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDeviceOnline' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveAlert' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSettings' : IDL.Func([UserSettings], [], []),
  'updateDeviceStatus' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Alert = IDL.Record({
    'latitude' : IDL.Float64,
    'resolved' : IDL.Bool,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'locationName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'emergencyContact' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserSettings = IDL.Record({
    'safeZoneCenterLat' : IDL.Float64,
    'safeZoneCenterLng' : IDL.Float64,
    'alertStartHour' : IDL.Nat,
    'alarmSoundEnabled' : IDL.Bool,
    'safeZoneRadius' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlert' : IDL.Func([Alert], [], []),
    'addLocation' : IDL.Func([Location], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocationHistory' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDeviceOnline' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveAlert' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSettings' : IDL.Func([UserSettings], [], []),
    'updateDeviceStatus' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };